### ISSUE TITLE
Cambios relacionados con el gitignore y archivos .env

### ISSUE THREAD

**Issue by DiegoSHS** [MaraGarciaAldama/SACI#3]
El gitignore debe ser cambiado para ignorar los archivos .env, cuando sea pertinente compartir con los contribuyentes la cadena de conexión a MongoDB Atlas para tener acceso cada quien con su .env local

**Comment by DavidLozanoHernandez** [comment]
Se actualizo la conexion de MongoDB Atlas.

**Comment by DiegoSHS** [comment]
Revisión completada, todo correcto, verificado en el pull request #4
